### Bu bolumde tensorflow 2.1'de veri setini değişik şekillerde gruplandırmayı öğreneceğiz.


Lütfen ekteki resme bakınız. 

In [1]:

import  tensorflow as tf
import numpy as np
    


In [2]:
#1 adım şekildeki matris ve vektor oluşturulur 
x=np.array([[2,2,3],[3,4,5],[4,5,7],[8,9,10],[2,3,4],[2,0,4]])
y=np.array([0,1,2,3,4,5])

In [3]:
#daha sonra x, y tensore donusturulur.
x=tf.convert_to_tensor(x,dtype=tf.float32)
y=tf.convert_to_tensor(y,dtype=tf.float32)


In [4]:
#2 adım olarak db denilen tensor yapısı elde edilir. 
#Bu yapı hem x ve y yi birleştirir hem de
#x ye y yi dilimlere ayırır. 
db = tf.data.Dataset.from_tensor_slices((x,y))

In [5]:
#3 adımda şekilde görüldüğü gibi tek tek dilimlere ayrılan 
#kısımlar istenilen sayıda (burada 2 olrak verilmiş) gruba ayrılır.
#ve bu patern 3 defa tekrar eder. 
db = db.batch(2).repeat(3)


In [6]:
for element in db: 
    print(element) 

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 2., 3.],
       [3., 4., 5.]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 1.], dtype=float32)>)
(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 4.,  5.,  7.],
       [ 8.,  9., 10.]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>)
(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 3., 4.],
       [2., 0., 4.]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([4., 5.], dtype=float32)>)
(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 2., 3.],
       [3., 4., 5.]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 1.], dtype=float32)>)
(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 4.,  5.,  7.],
       [ 8.,  9., 10.]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>)
(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
arra

In [7]:
print(list(db.as_numpy_iterator())) 

[(array([[2., 2., 3.],
       [3., 4., 5.]], dtype=float32), array([0., 1.], dtype=float32)), (array([[ 4.,  5.,  7.],
       [ 8.,  9., 10.]], dtype=float32), array([2., 3.], dtype=float32)), (array([[2., 3., 4.],
       [2., 0., 4.]], dtype=float32), array([4., 5.], dtype=float32)), (array([[2., 2., 3.],
       [3., 4., 5.]], dtype=float32), array([0., 1.], dtype=float32)), (array([[ 4.,  5.,  7.],
       [ 8.,  9., 10.]], dtype=float32), array([2., 3.], dtype=float32)), (array([[2., 3., 4.],
       [2., 0., 4.]], dtype=float32), array([4., 5.], dtype=float32)), (array([[2., 2., 3.],
       [3., 4., 5.]], dtype=float32), array([0., 1.], dtype=float32)), (array([[ 4.,  5.,  7.],
       [ 8.,  9., 10.]], dtype=float32), array([2., 3.], dtype=float32)), (array([[2., 3., 4.],
       [2., 0., 4.]], dtype=float32), array([4., 5.], dtype=float32))]
